apiVersion: v1
kind: Service
metadata:
  name: fee-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8780
    targetPort: 8780
  selector:
    app: fee-service
