apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fee-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fee-service
    spec:
      containers:
      - name: fee-service
        image: home-office/fee-service:0.1.0
        ports:
        - containerPort: 8780
