apiVersion: v1
kind: Service
metadata:
  name: circumstance-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8980
    targetPort: 8980
  selector:
    app: circumstance-service
